[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[features]
rt-tokio = ["dep:tokio", "async_thrift/rt-tokio", "thrift/rt-tokio"]
rt-async-std = ["dep:async-std", "async_thrift/rt-async-std", "thrift/rt-async-std"]

[dependencies]
async_thrift = {path = "../async_thrift"}

async-trait = "0.1.83"
criterion = { version = "0.5.1", features = ["async_std", "async_tokio", "html_reports"] }
futures = "0.3.31"
thrift = {path = "../thrift"}

tokio = { version = "1.41.0", features = ["rt-multi-thread", "time"], optional=true}
async-std = {version = "1.9.0", optional = true}

[[bench]]
name = "client"
harness = false
